// UltraPokechill localization helpers. ASCII source; non-ASCII text is escaped deliberately.
(function () {
  const storageKey = "ultraPokechill.language";
  const data = {
    en: { ui: {
    "language.label": "Language",
    "language.english": "English",
    "language.portuguese": "Portuguese",
    "language.notice": "Portuguese translation is not 100% complete yet.",
    "menu.travel": "Travel",
    "menu.vs": "VS",
    "menu.items": "Items",
    "menu.team": "Team",
    "menu.dex": "Dex",
    "menu.shop": "Poke-Mart",
    "menu.training": "Training",
    "menu.genetics": "Genetics",
    "menu.mysteryGift": "Mystery Gift",
    "menu.exportReward": "Export Reward",
    "menu.wonderTrade": "Wonder Trade",
    "menu.megaDimension": "Mega Dimension",
    "menu.dictionary": "Dictionary",
    "menu.settings": "Settings",
    "menu.guide": "Guide",
    "menu.fullScreen": "Full Screen",
    "settings.export": "Export Data",
    "settings.import": "Import Data",
    "settings.text": "Data to Text",
    "settings.mods": "Mods",
    "settings.theme": "Theme",
    "settings.hideGot": "Hide non-new Pokemon got in summary",
    "settings.alternateRotation": "Subtract 1 to current Wild Area rotation",
    "settings.gameModifiers": "Game modifiers",
    "settings.credits": "Credits",
    "settings.wipe": "Wipe Data",
    "guide.title": "Game Guide",
    "starter.title": "Select a starter!",
    "starter.mods": "Mods",
    "common.default": "default",
    "common.dark": "dark",
    "common.verdant": "verdant",
    "common.lilac": "lilac",
    "common.cherry": "cherry",
    "common.onyx": "onyx",
    "common.coral": "coral",
    "common.oled": "oled",
    "common.disabled": "disabled",
    "common.enabled": "enabled",
    "move.power": "Power",
    "move.noEffects": "No additional effects",
    "move.affectedBy": "Affected by",
    "move.restricted": "This move is restricted and only one of them can be present in the active moves at a time",
    "move.signatureNote": "This is a Signature Move. Signature moves will automatically be learnt at level 100",
    "move.eggNote": "This is an Egg Move. Egg moves can be learnt with genetics when using this Pokemon as a host, using a sample that knows said egg move (usually in the form of Signature moves), at regular move transfer odds",
    "ability.common": "Common Ability",
    "ability.uncommon": "Uncommon Ability",
    "ability.rare": "Rare Ability",
    "dictionary.common": "(Common)",
    "dictionary.uncommon": "(Uncommon)",
    "dictionary.rare": "(Rare)",
    "dictionary.learnableByTypes": "Learnable by {types} types {rarity}",
    "dictionary.hiddenAbilityOf": "Additionally, appears as the Hidden Ability of {pokemon}",
    "dictionary.abilityOnlyHidden": "This ability can only appear as the Hidden Ability of {pokemon}",
    "dictionary.abilityUnobtainable": "This ability is currently unobtainable :(",
    "dictionary.moveSignatureOnly": "This move can only appear as the Signature Move of {pokemon}",
    "dictionary.moveEggOf": "and the Egg Move of {pokemon}"
}, terms: {}, moves: {}, guides: {}, replacements: {} },
    pt: { ui: {
    "language.label": "Idioma",
    "language.english": "Ingles",
    "language.portuguese": "Portugues",
    "language.notice": "A traducao em Portugues ainda nao esta 100% completa.",
    "menu.travel": "Viajar",
    "menu.vs": "VS",
    "menu.items": "Itens",
    "menu.team": "Time",
    "menu.dex": "Dex",
    "menu.shop": "Loja",
    "menu.training": "Treino",
    "menu.genetics": "Genetica",
    "menu.mysteryGift": "Presente",
    "menu.exportReward": "Recompensa",
    "menu.wonderTrade": "Troca Surpresa",
    "menu.megaDimension": "Mega Dimensao",
    "menu.dictionary": "Dicionario",
    "menu.settings": "Opcoes",
    "menu.guide": "Guia",
    "menu.fullScreen": "Tela Cheia",
    "settings.export": "Exportar dados",
    "settings.import": "Importar dados",
    "settings.text": "Dados em texto",
    "settings.mods": "Mods",
    "settings.theme": "Tema",
    "settings.hideGot": "Ocultar Pokemon repetidos no resumo",
    "settings.alternateRotation": "Subtrair 1 da rotacao atual da Area Selvagem",
    "settings.gameModifiers": "Modificadores do jogo",
    "settings.credits": "Creditos",
    "settings.wipe": "Apagar dados",
    "guide.title": "Guia do jogo",
    "starter.title": "Escolha um inicial!",
    "starter.mods": "Mods",
    "common.default": "padrao",
    "common.dark": "escuro",
    "common.verdant": "verde",
    "common.lilac": "lilas",
    "common.cherry": "cereja",
    "common.onyx": "onix",
    "common.coral": "coral",
    "common.oled": "oled",
    "common.disabled": "desativado",
    "common.enabled": "ativado",
    "move.power": "Poder",
    "move.noEffects": "Sem efeitos adicionais",
    "move.affectedBy": "Afetado por",
    "move.restricted": "Este golpe e restrito e apenas um deles pode estar nos golpes ativos por vez",
    "move.signatureNote": "Este e um Golpe Assinatura. Golpes Assinatura sao aprendidos automaticamente no nivel 100",
    "move.eggNote": "Este e um Golpe Ovo. Golpes Ovo podem ser aprendidos com Genetica usando este Pokemon como host e uma amostra que conheca o golpe, normalmente por meio de Golpes Assinatura, nas chances normais de transferencia",
    "ability.common": "Habilidade comum",
    "ability.uncommon": "Habilidade incomum",
    "ability.rare": "Habilidade rara",
    "dictionary.common": "(Comum)",
    "dictionary.uncommon": "(Incomum)",
    "dictionary.rare": "(Raro)",
    "dictionary.learnableByTypes": "Aprendido por tipos {types} {rarity}",
    "dictionary.hiddenAbilityOf": "Tambem aparece como Habilidade Oculta de {pokemon}",
    "dictionary.abilityOnlyHidden": "Esta habilidade so pode aparecer como Habilidade Oculta de {pokemon}",
    "dictionary.abilityUnobtainable": "Esta habilidade nao pode ser obtida no momento :(",
    "dictionary.moveSignatureOnly": "Este golpe so pode aparecer como Golpe Assinatura de {pokemon}",
    "dictionary.moveEggOf": "e como Golpe Ovo de {pokemon}"
}, terms: {
    "normal": "Normal",
    "fire": "Fogo",
    "water": "Agua",
    "electric": "Eletrico",
    "grass": "Grama",
    "ice": "Gelo",
    "fighting": "Lutador",
    "poison": "Venenoso",
    "ground": "Terrestre",
    "flying": "Voador",
    "psychic": "Psiquico",
    "bug": "Inseto",
    "rock": "Pedra",
    "ghost": "Fantasma",
    "dragon": "Dragao",
    "dark": "Sombrio",
    "steel": "Aco",
    "fairy": "Fada",
    "physical": "Fisico",
    "special": "Especial",
    "status": "Status",
    "all": "Todos",
    "type": "tipo",
    "level": "nivel",
    "division": "divisao",
    "evolution": "evolucao",
    "ability": "habilidade",
    "shiny": "shiny",
    "signature": "assinatura",
    "ribbon": "fita",
    "tag": "marcador",
    "sort": "ordenar",
    "default": "padrao",
    "disabled": "desativado",
    "enabled": "ativado",
    "none": "nenhum",
    "common": "comum",
    "uncommon": "incomum",
    "rare": "raro",
    "hidden": "oculto",
    "burn": "Queimadura",
    "freeze": "Congelamento",
    "paralysis": "Paralisia",
    "poisoned": "Envenenado",
    "sleep": "Sono",
    "confused": "Confuso",
    "sunny": "Ensolarado",
    "rainy": "Chuvoso",
    "sandstorm": "Tempestade de Areia",
    "hail": "Granizo",
    "foggy": "Neblina",
    "electricTerrain": "Terreno Eletrico",
    "grassyTerrain": "Terreno de Grama",
    "mistyTerrain": "Terreno Enevoado",
    "lightScreen": "Tela de Luz",
    "safeguard": "Salvaguarda"
}, moves: {
    "quickAttack": "Ataque R\u00e1pido",
    "tackle": "Investida",
    "doubleSlap": "Tapa Duplo",
    "cut": "Cortar",
    "leer": "Encarar",
    "growl": "Rosnadura",
    "swagger": "Arrog\u00e2ncia",
    "doubleHit": "Golpe Duplo",
    "swift": "Ataque Veloz",
    "dizzyPunch": "Soco Estonteante",
    "stomp": "Pisotear",
    "screech": "Agudo",
    "smellingSalts": "Ess\u00eancia Salgada",
    "facade": "Fachada",
    "slash": "Talho",
    "extremeSpeed": "Velocidade Extrema",
    "strength": "For\u00e7a",
    "hyperVoice": "Hipervoz",
    "bodyPress": "Apert\u00e3o Corporal",
    "hyperBeam": "Hiper-raio",
    "gigaImpact": "Gigaimpacto",
    "swordsDance": "Dan\u00e7a das Espadas",
    "ember": "Brasa",
    "fireSpin": "Chama Furac\u00e3o",
    "flameCharge": "Ataque de Chamas",
    "incinerate": "Incinerar",
    "fireFang": "Presas de Fogo",
    "firePunch": "Soco de Fogo",
    "sunnyDay": "Dia Ensolarado",
    "flamethrower": "Lan\u00e7a-chamas",
    "heatWave": "Onda de Calor",
    "fireBlast": "Rajada de Fogo",
    "flareBlitz": "Blitz de Labaredas",
    "overheat": "Superaquecimento",
    "nuzzle": "Chamego",
    "thunderShock": "Trovoada de Choques",
    "thunderWave": "Onda de Trov\u00e3o",
    "chargeBeam": "Carga de Raio",
    "electroWeb": "Teia El\u00e9trica",
    "thunderFang": "Presa Trovejante",
    "thunderPunch": "Soco Trovoada",
    "thunderbolt": "Rel\u00e2mpago",
    "discharge": "Descarga",
    "electricTerrain": "Terreno El\u00e9trico",
    "thunder": "Trov\u00e3o",
    "voltSwitch": "Troca El\u00e9trica",
    "wildCharge": "Ataque Selvagem",
    "supercellSlam": "Pancada Pilhada",
    "mudSlap": "Tapa de Lama",
    "magnitude": "Magnitude",
    "mudShot": "Tiro de Lama",
    "bulldoze": "Tremor",
    "sandstorm": "Tempestade de Areia",
    "scorchingSands": "Areias Ardentes",
    "rototiller": "Rototiller",
    "earthquake": "Terremoto",
    "dig": "Cavar",
    "earthPower": "Poder da Terra",
    "stompingTantrum": "Birra",
    "bulletPunch": "Soco Proj\u00e9til",
    "metalClaw": "Garra de Metal",
    "magnetBomb": "Bomba \u00cdm\u00e3",
    "mirrorShot": "Tiro no Espelho",
    "steelWing": "Asa de A\u00e7o",
    "ironHead": "Cabe\u00e7a de Ferro",
    "flashCannon": "Canh\u00e3o de Flash",
    "ironTail": "Cauda de Ferro",
    "smartStrike": "Golpe Preciso",
    "metalSound": "Som de Metal",
    "ironDefense": "Defesa de Ferro",
    "peck": "Bicada",
    "gust": "Lufada de Vento",
    "skyDrop": "Queda Livre",
    "dualWingbeat": "Ataque de Asa Duplo",
    "acrobatics": "Acrob\u00e1tico",
    "airShlash": "Golpe de Ar",
    "drillPeck": "Bico Broca",
    "tailwind": "Vento de Cauda",
    "fly": "Voar",
    "featherDance": "Dan\u00e7a das Penas",
    "bounce": "Ricochete",
    "hurricane": "Furac\u00e3o",
    "acid": "\u00c1cido",
    "poisonSting": "Ferr\u00e3o Venenoso",
    "smog": "Nevoeiro de Fuma\u00e7a",
    "poisonPowder": "P\u00f3 Venenoso",
    "toxic": "T\u00f3xico",
    "poisonFang": "Presa Venenosa",
    "sludge": "Ataque de Lama",
    "crossPoison": "Corte-veneno",
    "poisonJab": "Golpe Envenenado",
    "sludgeBomb": "Bomba de Lodo",
    "sludgeWave": "Onda de Lama",
    "coil": "Enroscar",
    "acidArmor": "Armadura \u00c1cida",
    "acidSpray": "Spray \u00c1cido",
    "iceShard": "Caco de Gelo",
    "powderSnow": "Neve em P\u00f3",
    "icicleSpear": "Lan\u00e7a Congelada",
    "hail": "Granizo",
    "icyWind": "Vento Congelante",
    "avalanche": "Avalanche",
    "frostBreath": "Respira\u00e7\u00e3o de Gelo",
    "auroraBeam": "Raio Aurora",
    "iceFang": "Presa de Gelo",
    "icePunch": "Soco de Gelo",
    "iceBeam": "Raio Congelante",
    "blizzard": "Nevasca",
    "icicleCrash": "Choque de Gelo",
    "safeguard": "Salvaguarda",
    "twineedle": "Agulha Dupla",
    "furyCutter": "Cortador de F\u00faria",
    "infestation": "Infesta\u00e7\u00e3o",
    "pinMissile": "M\u00edssil de Espinhos",
    "stickyWeb": "Teia Pegajosa",
    "struggleBug": "Ira de Inseto",
    "bugBite": "Picada",
    "bugBuzz": "Zumbido de Inseto",
    "signalBeam": "Feixe Sinalizador",
    "silverWind": "Vento Prateado",
    "xScissor": "Tesoura X",
    "firstImpression": "Primeira Impress\u00e3o",
    "stringShot": "Estilingada",
    "uTurn": "Fazer Retorno",
    "savageStinger": "Casulo Brutal",
    "quiverDance": "Dan\u00e7a Vibrat\u00f3ria",
    "waterGun": "Rev\u00f3lver d'\u00c1gua",
    "aquaJet": "Aqua Jato",
    "whirlpool": "Redemoinho",
    "waterPulse": "Pulso d'\u00c1gua",
    "chillingWater": "\u00c1gua Fria",
    "bubbleBeam": "Jato de Bolhas",
    "rainDance": "Dan\u00e7a da Chuva",
    "waterfall": "Cachoeira",
    "scald": "Escaldada",
    "liquidation": "Aquar\u00edete",
    "aquaTail": "Aqua Cauda",
    "surf": "Surfar",
    "muddyWater": "\u00c1gua Barrenta",
    "hydroPump": "Jato d'\u00c1gua",
    "leafage": "Folhagem",
    "vineWhip": "Chicote de Vinha",
    "magicalLeaf": "Folha M\u00e1gica",
    "bulletSeed": "Proj\u00e9til de Semente",
    "razorLeaf": "Folha Navalha",
    "stunSpore": "P\u00f3 Atordoante",
    "ragePowder": "P\u00f3 da Raiva",
    "leafBlade": "L\u00e2mina de Folha",
    "energyBall": "Bola de Energia",
    "solarBeam": "Raio Solar",
    "solarBlade": "L\u00e2mina Solar",
    "seedBomb": "Bomba de Sementes",
    "cottonSpore": "Esporo de Algod\u00e3o",
    "spore": "Esporos",
    "grassyTerrain": "Terreno de Plantas",
    "leafStorm": "Tempestade de Folhas",
    "rockSmash": "Esmagamento de Pedras",
    "vacuumWave": "Onda de V\u00e1cuo",
    "armThrust": "Golpe de Bra\u00e7o",
    "powerupPunch": "Soco Empoderador",
    "stormThrow": "Lan\u00e7amento de Tempestade",
    "lowSweep": "Movimento Baixo",
    "forcePalm": "Palma da For\u00e7a",
    "brickBreak": "Quebra-telha",
    "skyUppercut": "Direto Celeste",
    "hammerArm": "Bra\u00e7o de Martelo",
    "auraSphere": "Aura Esf\u00e9rica",
    "bulkUp": "For\u00e7a Bruta",
    "crossChop": "Golpe Cruzado",
    "closeCombat": "Corpo-a-corpo",
    "superpower": "Superpoder",
    "focusBlast": "Explos\u00e3o Focalizada",
    "confusion": "Confus\u00e3o",
    "psybeam": "Feixe Ps\u00edquico",
    "futureSight": "Vis\u00e3o do Futuro",
    "psychoCut": "Corte Ps\u00edquico",
    "psychicFangs": "Caninos Ps\u00edquicos",
    "zenHeadbut": "Cabe\u00e7ada Zen",
    "psychic": "Ps\u00edquico",
    "extrasensory": "Extrassensorial",
    "amnesia": "Amn\u00e9sia",
    "barrier": "Barreira",
    "agility": "Agilidade",
    "calmMind": "Mente Calma",
    "psychoBoost": "Impulso Ps\u00edquico",
    "reflect": "Refletir",
    "rockThrow": "Lan\u00e7amento de Rocha",
    "accelerock": "Rocha Veloz",
    "rockBlast": "Explos\u00e3o de Rocha",
    "rollout": "Rolagem",
    "ancientPower": "Poder Ancestral",
    "smackDown": "Derrubada",
    "rockTomb": "Tumba de Rochas",
    "rockSlide": "Deslize de Pedras",
    "powerGem": "Gema Poderosa",
    "stoneEdge": "Gume de Pedra",
    "meteorBeam": "Raio Mete\u00f3rico",
    "rockPolish": "Polidor de Rocha",
    "wrathOfTheLand": "Ira da Terra",
    "lick": "Lambida",
    "shadowSneak": "Furtividade nas Sombras",
    "confuseRay": "Raio da Confus\u00e3o",
    "willOWisp": "Fogo F\u00e1tuo",
    "ominousWind": "Vento Ominoso",
    "hex": "Feiti\u00e7o",
    "shadowClaw": "Garra Sombria",
    "shadowPunch": "Soco Sombrio",
    "shadowBall": "Bola Sombria",
    "phantomForce": "Golpe Fantasma",
    "twister": "Twister",
    "dragonTail": "Cauda do Drag\u00e3o",
    "dualChop": "Pancada Dupla",
    "dragonBreath": "Sopro do Drag\u00e3o",
    "dragonClaw": "Garra de Drag\u00e3o",
    "scaleShot": "Disparo Escamoso",
    "dragonPulse": "Pulso do Drag\u00e3o",
    "dragonRush": "Investida do Drag\u00e3o",
    "outrage": "Ultraje",
    "dracoMeteor": "Meteoro do Drag\u00e3o",
    "dragonDance": "Dan\u00e7a do Drag\u00e3o",
    "pursuit": "Persegui\u00e7\u00e3o",
    "snarl": "Rosnado",
    "bite": "Mordida",
    "feintAttack": "Ataque Dissimulado",
    "knockOff": "Derrubar",
    "crunch": "Mastigada",
    "darkPulse": "Pulso Sombrio",
    "honeClaws": "Garras Afiadas",
    "nightDaze": "Ofuscamento Noturno",
    "nightSlash": "Talho Noturno",
    "fakeTears": "L\u00e1grimas Falsas",
    "nastyPlot": "Trama Maldosa",
    "memento": "Recorda\u00e7\u00e3o",
    "trickRoom": "Truque de Agilidade",
    "embargo": "Embargo",
    "brutalSwing": "Balan\u00e7o Violento",
    "disarmingVoice": "Voz Desarmante",
    "drainingKiss": "Beijo Drenante",
    "fairyWind": "Vento de Fada",
    "echoedVoice": "Voz Ecoante",
    "spiritBreak": "Quebra Espiritual",
    "dazzlingGleam": "Clar\u00e3o Deslumbrante",
    "playRough": "Jogo Duro",
    "moonblast": "Explos\u00e3o Lunar",
    "babydollEyes": "Olhos Ternos",
    "charm": "Encantar",
    "sweetKiss": "Beijo Doce",
    "lightScreen": "Tela de Luz",
    "acupressure": "Acupress\u00e3o",
    "batonPass": "Passar o Bast\u00e3o",
    "bellyDrum": "Tambor M\u00e1ximo",
    "boomburst": "Rajada Explosiva",
    "eggBomb": "Ovo Bomba",
    "cometPunch": "Soco de Cometa",
    "payDay": "Dia de Pagamento",
    "teatime": "Hora do Ch\u00e1",
    "metronome": "Metr\u00f4nomo",
    "mimic": "M\u00edmica",
    "meFirst": "Primeiro Eu",
    "burnUp": "Chama Final",
    "magmaStorm": "Tempestade de Magma",
    "inferno": "Inferno",
    "aquaStep": "Passo Aqu\u00e1tico",
    "hydroCannon": "Hidro Canh\u00e3o",
    "gigatonHammer": "Martelo Gigat\u00f4nico",
    "razorShell": "Concha Navalha",
    "electroBall": "Bola El\u00e9trica",
    "charge": "Carga",
    "appleAcid": "Ma\u00e7\u00e3 \u00c1cida",
    "frenzyPlant": "Planta Mortal",
    "trailblaze": "Desbravar",
    "auraWheel": "Roda de Aura",
    "freezeDry": "Liofiliza\u00e7\u00e3o",
    "venoshock": "Venochoque",
    "highHorsepower": "Pot\u00eancia Equina",
    "blazeKick": "Chute Labareda",
    "pyroBall": "Bola Incendi\u00e1ria",
    "braveBird": "P\u00e1ssaro Bravo",
    "snipeShot": "Tiro Certeiro",
    "moongeistBeam": "Feixe Espectral",
    "sunsteelStrike": "Ataque Solara\u00e7o",
    "rockWrecker": "Demolidor de Pedras",
    "aeroblast": "Explos\u00e3o A\u00e9rea",
    "sacredFire": "Fogo Sagrado",
    "crabhammer": "Martelo Caranguejo",
    "iceHammer": "Martelo de Gelo",
    "dragonDarts": "Dardos Drac\u00f4nicos",
    "hiJumpKick": "Chute de Pulo Alto",
    "falseSurrender": "Rendi\u00e7\u00e3o Falsa",
    "headCharge": "Ataque de Cabe\u00e7a",
    "megahorn": "Megachifre",
    "needleArm": "Bra\u00e7o de Agulha",
    "anchorShot": "Tiro de \u00c2ncora",
    "darkestLariat": "Lariat Escuro",
    "dragonEnergy": "Energia Drac\u00f4nica",
    "thunderCage": "Pris\u00e3o El\u00e9trica",
    "mindBlown": "Explos\u00e3o Mental",
    "sparklingAria": "Aria Cintilante",
    "floralHealing": "Cura das Flores",
    "revelationDance": "Dan\u00e7a Reveladora",
    "weatherBall": "Esfera Clim\u00e1tica",
    "poisonTail": "Cauda Venenosa",
    "heatCrash": "Choque de Calor",
    "chatter": "Falat\u00f3rio",
    "voltTackle": "Investida Trov\u00e3o",
    "zingZap": "Eletro Zap",
    "lovelyKiss": "Beijo Amoroso",
    "crushGrip": "Aperto Esmagador",
    "spacialRend": "Lacera\u00e7\u00e3o Espacial",
    "fishiousRend": "Branquimordida",
    "armorCannon": "Canh\u00e3o de Armadura",
    "bitterBlade": "L\u00e2mina Cruel",
    "noRetreat": "Sem Recuo",
    "storedPower": "Poder Armazenado",
    "camouflage": "Camuflagem",
    "tailGlow": "Cauda Ardente",
    "flyingPress": "Aperto Voador",
    "mountainGale": "Vendaval Montanhoso",
    "jetPunch": "Soco Jato",
    "roarOfTime": "Rugido do Tempo",
    "doomDesire": "Desejo Cruel",
    "beakBlast": "Bico Explosivo",
    "shadowForce": "For\u00e7a das Sombras",
    "blueFlare": "Labareda Azul",
    "boltStrike": "Ataque de Raios",
    "glaciate": "Glaciar",
    "howl": "Uivo",
    "lunarDance": "Dan\u00e7a Lunar",
    "fairyLock": "Aprisionamento de Fada",
    "electrify": "Eletrificar",
    "forestCurse": "Maldi\u00e7\u00e3o da Floresta",
    "trickOrTreat": "Doces ou Travessuras",
    "magicPowder": "P\u00f3lvora M\u00e1gica",
    "mudSport": "Campo de Lama",
    "boneRush": "F\u00faria de Ossos",
    "clamp": "Capturar",
    "waterShuriken": "Estrela Ninja de \u00c1gua",
    "barrage": "Barricada",
    "psyshieldBash": "Pancada de Escudo Ps\u00edquico",
    "sketch": "Rascunho",
    "prismaticLaser": "Laser Prism\u00e1tico",
    "lusterPurge": "Purga de Esplendor",
    "mistBall": "Bola de N\u00e9voa",
    "dynamicPunch": "Soco Din\u00e2mico",
    "thunderousKick": "Chute Trovejante",
    "fieryWrath": "F\u00faria Ardente",
    "meteorAssault": "Ofensiva Mete\u00f3rica",
    "cottonGuard": "Prote\u00e7\u00e3o de Algod\u00e3o",
    "kingsShield": "Escudo do Rei",
    "drumBeating": "Toque do Tambor",
    "tropKick": "Chute Tropical",
    "clangingScales": "Batida de Escamas",
    "shiftGear": "Troca de Marcha",
    "kinesis": "Cinese",
    "relicSong": "Can\u00e7\u00e3o da Rel\u00edquia",
    "zapCannon": "Canh\u00e3o Zap",
    "triAttack": "Triataque",
    "judgment": "Julgamento",
    "rageFist": "Punho Feroz",
    "iceBall": "Bola de Gelo",
    "tripleAxel": "Pinote Triplo",
    "attackOrder": "Ordem de Ataque",
    "nobleRoar": "Rugido Nobre",
    "hyperDrill": "Hiperbroca",
    "fieryDance": "Dan\u00e7a Ardente",
    "torchSong": "Can\u00e7\u00e3o Ardente",
    "seedFlare": "Semente Ofuscante",
    "vCreate": "Cria\u00e7\u00e3o V",
    "dragonAscent": "Ascen\u00e7\u00e3o do Drag\u00e3o",
    "mysticalFire": "Fogo M\u00edstico",
    "sandsearStorm": "Tempestade Saibrosa",
    "splash": "Borrifada",
    "conversion": "Convers\u00e3o",
    "flameBurst": "Rajada de Chamas",
    "morningSun": "Sol da Manh\u00e3"
}, guides: {
    "addingMods": {
        "name": "Mods: Como adicionar mods",
        "description": "Mods sao opcionais. O jogo funciona sem mods, com poucos mods ou com varios mods ativos.<br><br><strong>Instalar pela Workshop</strong><br>Abra Opcoes, clique em Mods, entre na aba Workshop e clique em Install no mod desejado. Depois, ative o mod pela aba Installed.<br><br><strong>Instalar um arquivo .mod</strong><br>Abra Opcoes, clique em Mods e arraste o arquivo .mod para a area de importacao. Voce tambem pode clicar na area para selecionar o arquivo manualmente.<br><br><strong>Ativar ou desativar</strong><br>Use o botao de cada card. Alguns mods aplicam na hora; outros ficam mais seguros depois de recarregar a pagina."
    },
    "creatingMods": {
        "name": "Mods: Como criar mods (Em breve)",
        "description": "Em breve."
    },
    "inspecting": {
        "name": "Inspecionar",
        "description": "Clique com o botao direito ou segure o toque na maioria dos elementos para ver mais informacoes. Isso tambem funciona dentro de algumas janelas de informacao.<br><br>Voce pode inspecionar areas, treinadores, golpes, efeitos de status, Pokemon selvagens, Pokemon do time e itens."
    },
    "stats": {
        "name": "Batalha: atributos",
        "description": "Cada especie de Pokemon tem atributos base que definem os atributos reais em cada nivel.<br><br>Os atributos decidem quanto dano o Pokemon causa e recebe. Velocidade decide com que frequencia ele usa golpes.<br><br>IVs multiplicam os atributos base e podem aumentar quando voce consegue copias do mesmo Pokemon."
    },
    "abilities": {
        "name": "Batalha: habilidades",
        "description": "Habilidades sao caracteristicas que um Pokemon pode ter. Elas sao sorteadas, mas algumas aparecem apenas em tipos especificos. Existem habilidades comuns, incomuns e raras.<br><br>Habilidades ocultas dependem da especie e precisam ser desbloqueadas. Depois disso, ficam ativas junto da habilidade normal."
    },
    "experience": {
        "name": "Batalha: experiencia",
        "description": "Pokemon ganham experiencia ao derrotar inimigos, e parte dela e dividida com o time mesmo quando algum membro esta derrotado.<br><br>O ganho depende da diferenca de nivel. Diferencas maiores podem aumentar bastante a experiencia recebida. Um Pokemon 10 niveis acima nao recebe experiencia."
    },
    "moves": {
        "name": "Batalha: golpes",
        "description": "Pokemon aprendem golpes a cada 7 niveis. Os golpes podem ser trocados ao clicar com o botao direito ou segurar toque em um Pokemon do time.<br><br>Golpes de dano sao fisicos ou especiais. A categoria define quais atributos entram no calculo de dano.<br><br>Alguns Pokemon tem golpes assinatura. Alguns golpes sao restritos, e apenas um golpe restrito pode ficar equipado no Pokemon ativo."
    },
    "stab": {
        "name": "Batalha: STAB",
        "description": "Quando um Pokemon usa um golpe de dano do mesmo tipo que ele, o dano recebe multiplicador x1.5. Isso se chama STAB.<br><br>Pokemon de tipo unico recebem +0.2 de bonus extra de STAB."
    },
    "crossStab": {
        "name": "Batalha: Cross-Power",
        "description": "Quando um Pokemon usa um golpe de dano de tipo diferente do golpe de dano anterior, esse golpe recebe multiplicador x1.3. A barra do golpe mostra um padrao cruzado quando isso esta ativo."
    },
    "battleFatigue": {
        "name": "Batalha: fadiga",
        "description": "Pokemon perdem uma pequena parte da vida maxima ao atacar. Pokemon mais resistentes conseguem lutar por mais tempo porque HP, Defesa e Defesa Especial reduzem esse desgaste."
    },
    "statusEffects": {
        "name": "Batalha: status",
        "description": "Alguns golpes aplicam efeitos como queimadura, veneno, congelamento, paralisia, sono ou confusao.<br><br>Voce pode inspecionar esses efeitos com botao direito ou toque longo.<br><br>Efeitos de status e mudancas temporarias de atributo duram alguns turnos."
    },
    "buffsDebuffs": {
        "name": "Batalha: buffs e debuffs",
        "description": "Aumentos e reducoes de atributos duram 3 turnos por padrao, exceto reducoes de Velocidade, que duram 2 turnos.<br><br>Buffs e debuffs do mesmo valor nao acumulam entre si, mas valores diferentes podem acumular."
    },
    "weather": {
        "name": "Batalha: clima",
        "description": "Alguns golpes alteram o clima ou o terreno da batalha. Esses efeitos mudam o dano de certos tipos ou regras temporarias da luta.<br><br>Climas alterados duram 15 turnos e so podem ser trocados depois de 30 turnos."
    },
    "shiny": {
        "name": "Pokemon shiny",
        "description": "Pokemon podem vir shiny com chance base de 1/400. Essa chance pode ser aumentada por outros recursos.<br><br>Pokemon shiny causam 15% mais dano. O visual shiny pode ser ocultado no menu de golpes sem perder o bonus."
    },
    "genetics": {
        "name": "Genetica: guia rapido",
        "description": "Genetica permite modificar um Pokemon alem do normal da especie.<br><br><strong>Mutacao shiny</strong>: pode passar shiny para membros da mesma familia.<br><br><strong>Aumento de IV</strong>: operacoes podem aumentar IVs do host.<br><br><strong>Heranca de golpes</strong>: alguns golpes podem ser herdados de uma amostra compativel."
    },
    "compatibility": {
        "name": "Genetica: compatibilidade",
        "description": "Compatibilidade mede o quanto a amostra parece com o host. Isso influencia chances de heranca e mutacao shiny.<br><br>Compartilhar tipos aumenta compatibilidade. Ser da mesma linha evolutiva da compatibilidade maxima."
    },
    "powerCost": {
        "name": "Genetica: custo de poder",
        "description": "Custo de poder define quanto tempo uma operacao genetica demora. Ele depende da divisao do host; divisoes mais altas aumentam bastante o tempo necessario."
    }
}, replacements: {
    "No additional effects": "Sem efeitos adicionais",
    "Decreases Attack by 50%": "Reduz o Ataque em 50%",
    "Decreases enemy Attack by 50%": "Reduz o Ataque do inimigo em 50%",
    "Decreases enemy Defense by 50%": "Reduz a Defesa do inimigo em 50%",
    "Decreases enemy Special Attack by 50%": "Reduz o Ataque Especial do inimigo em 50%",
    "Decreases enemy Special Defense by 50%": "Reduz a Defesa Especial do inimigo em 50%",
    "Increases Attack by 50%": "Aumenta o Ataque em 50%",
    "Increases Defense by 50%": "Aumenta a Defesa em 50%",
    "Attacks x1.2 faster than usual": "Ataca x1.2 mais rapido que o normal",
    "Hits 2 times": "Acerta 2 vezes",
    "Hits 2-5 times": "Acerta 2-5 vezes"
} }
  };

  function normalizeLanguage(value) { return value === "pt" ? "pt" : "en"; }
  function getLanguage() {
    if (typeof saved !== "undefined" && saved.language) return normalizeLanguage(saved.language);
    try { return normalizeLanguage(localStorage.getItem(storageKey)); } catch (error) { return "en"; }
  }
  function setLanguage(value) {
    const language = normalizeLanguage(value);
    if (typeof saved !== "undefined") saved.language = language;
    try { localStorage.setItem(storageKey, language); } catch (error) {}
    document.documentElement.lang = language === "pt" ? "pt-BR" : "en";
    applyStaticTranslations();
    refreshRenderedText();
    if (typeof saveGame === "function") saveGame();
  }
  function t(key, fallback = "") {
    const language = getLanguage();
    return data[language]?.ui?.[key] || data.en.ui[key] || fallback || key;
  }
  function formatName(id, fallback, kind) {
    const language = getLanguage();
    if (language === "en") return fallback;
    const pack = data[language];
    if (kind === "move" && pack.moves[id]) return pack.moves[id];
    if (pack.terms[id]) return pack.terms[id];
    return fallback;
  }
  function guideName(id, fallback) {
    const language = getLanguage();
    return data[language]?.guides?.[id]?.name || fallback;
  }
  function guideDescription(id, fallback) {
    const language = getLanguage();
    return data[language]?.guides?.[id]?.description || fallback;
  }
  const ptTypeLabels = {
    Normal: "Normal",
    Fire: "Fogo",
    Flame: "Fogo",
    Water: "Agua",
    Electric: "Eletrico",
    Grass: "Grama",
    Ice: "Gelo",
    Fighting: "Lutador",
    Poison: "Venenoso",
    Ground: "Terrestre",
    Flying: "Voador",
    Psychic: "Psiquico",
    Bug: "Inseto",
    Rock: "Pedra",
    Ghost: "Fantasma",
    Dragon: "Dragao",
    Dark: "Sombrio",
    Steel: "Aco",
    Fairy: "Fada"
  };
  const ptStatLabels = {
    "Attack": "o Ataque",
    "Defense": "a Defesa",
    "Special Attack": "o Ataque Especial",
    "Special Defense": "a Defesa Especial",
    "Speed": "a Velocidade",
    "all Stats": "todos os atributos",
    "highest stat": "o maior atributo"
  };
  function ptType(type) { return ptTypeLabels[type] || type; }
  function ptStat(stat) { return ptStatLabels[stat] || stat; }
  function ptAmount(amount) { return amount.replace(/^x/i, "x"); }
  const ptExactText = {
    "Common Ability": "Habilidade comum",
    "Uncommon Ability": "Habilidade incomum",
    "Rare Ability": "Habilidade rara",
    "Hidden Ability": "Habilidade Oculta",
    "Burn": "Queimadura",
    "Freeze": "Congelamento",
    "Paralysis": "Paralisia",
    "Poisoned": "Envenenado",
    "Sleep": "Sono",
    "Confused": "Confuso",
    "Embargo": "Embargo",
    "Sunny": "Sol",
    "Rainy": "Chuva",
    "Sandstorm": "Tempestade de Areia",
    "Hail": "Granizo",
    "Foggy": "Neblina",
    "Electric Terrain": "Campo Eletrico",
    "Grassy Terrain": "Campo de Grama",
    "Misty Terrain": "Campo Nebuloso",
    "Trick Room": "Trick Room",
    "Weird Room": "Weird Room",
    "Cross Room": "Cross Room",
    "Light Screen": "Light Screen",
    "Safeguard": "Safeguard",
    "Credits": "Creditos",
    "VS Trainers": "Treinadores VS",
    "Battle Frontier": "Fronteira de Batalha",
    "Battle Tower": "Torre de Batalha",
    "Battle Factory": "Fabrica de Batalha",
    "Battle Arena": "Arena de Batalha",
    "Wild Areas": "Areas Selvagens",
    "Dungeons": "Masmorras",
    "Training": "Treino",
    "Events": "Eventos",
    "Mega-Dimension": "Mega Dimensao",
    "Genetics": "Genetica",
    "Main Challenges": "Desafios principais",
    "Custom Challenges": "Desafios customizados",
    "Game Modifiers": "Modificadores do jogo",
    "Challenges": "Desafios",
    "Cheats": "Trapacas",
    "Hard Mode": "Modo dificil",
    "Nuzloke Mode": "Modo Nuzloke",
    "No IVs": "Sem IVs",
    "Longer AFK": "AFK mais longo",
    "Curry": "Curry",
    "Setting": "Opcao",
    "Keywords": "Palavras-chave",
    "Restricted Action": "Acao restrita",
    "Restricted Move": "Golpe restrito",
    "Reward Received": "Recompensa recebida",
    "Operation overview": "Resumo da operacao",
    "Operation finished!": "Operacao concluida!",
    "Are you sure you want to abort the operation?": "Tem certeza que quer abortar a operacao?",
    "Are you sure you want to delete all data forever?": "Tem certeza que quer apagar todos os dados para sempre?",
    "Are you sure you want to reset your save data?": "Tem certeza que quer resetar os dados do save?",
    "Yeah!": "Sim!",
    "Reset save": "Resetar save",
    "Nope": "Nao",
    "Start": "Iniciar",
    "Finish": "Concluir",
    "Abort": "Abortar",
    "Save and exit": "Salvar e sair",
    "Save and go!": "Salvar e ir!",
    "New Items!": "Novos itens!",
    "New items!": "Novos itens!",
    "No new items or Pokemon :(": "Nenhum item ou Pokemon novo :(",
    "All trainers defeated for now": "Todos os treinadores derrotados por enquanto",
    "All trainers defeated!": "Todos os treinadores derrotados!",
    "How about the Battle Frontier?": "Que tal a Fronteira de Batalha?",
    "All trainers defeated! How about the Battle Frontier?": "Todos os treinadores derrotados! Que tal a Fronteira de Batalha?",
    "New features unlocked!": "Novos recursos desbloqueados!",
    "New Wild Area unlocked": "Nova Area Selvagem desbloqueada",
    "New Dungeon:": "Nova Masmorra:",
    "Mystery Gift unlocked": "Presente Misterioso desbloqueado",
    "Export Reward unlocked": "Recompensa de Exportacao desbloqueada",
    "Poke-Mart unlocked": "Loja desbloqueada",
    "Training unlocked": "Treino desbloqueado",
    "Level Training unlocked": "Treino de nivel desbloqueado",
    "Battle Frontier unlocked": "Fronteira de Batalha desbloqueada",
    "Elite Event tab unlocked": "Aba de Eventos Elite desbloqueada",
    "Master League is now available in the Battle Frontier": "Master League agora esta disponivel na Fronteira de Batalha",
    "Tier I Event Raids unlocked": "Raids de Evento Tier I desbloqueadas",
    "Tier IV Event Raids unlocked": "Raids de Evento Tier IV desbloqueadas",
    "Area Pokemon": "Pokemon da area",
    "Area Items": "Itens da area",
    "Team Preview": "Previa do time",
    "Victory Rewards": "Recompensas da vitoria",
    "Factory Pokemon": "Pokemon da fabrica",
    "During raids: Gained the next abilities for everyone in your team:": "Durante raids: as proximas habilidades foram dadas para todo o seu time:",
    "Defeat increasingly difficult trainers and carve yourself a path of fame! You may unlock additional areas to explore as your progress": "Derrote treinadores cada vez mais dificeis e abra seu caminho para a fama. Voce pode desbloquear areas adicionais conforme progride",
    "The Battle Frontier houses different types of challenges under a specific division restriction that rotates every three days. Trainers fought here will reset every day": "A Fronteira de Batalha tem diferentes tipos de desafios sob uma restricao de divisao que muda a cada tres dias. Treinadores enfrentados aqui reiniciam todos os dias",
    "All Pokemon in Wild Areas might be caught by defeating them. Wild Areas rotate every day, so be sure to check out what can be caught today!": "Todos os Pokemon nas Areas Selvagens podem ser capturados ao derrota-los. Areas Selvagens mudam todos os dias, entao confira o que pode ser capturado hoje!",
    "Pokemon in Dungeons can't be caught, but they can drop useful items and EXP. Dungeons rotate every day aswell": "Pokemon em Masmorras nao podem ser capturados, mas podem derrubar itens uteis e EXP. Masmorras mudam todos os dias",
    "Create custom battles from your own pools and enemy teams. Import and export challenge codes to share them.": "Crie batalhas customizadas com seus proprios grupos e times inimigos. Importe e exporte codigos de desafio para compartilhar",
    "Every 12 hours, some of your Pokemon will contract Pokerus. This virus is entirely beneficial, and will add one level of compatibility to the Pokemon in genetics when used as a host": "A cada 12 horas, alguns dos seus Pokemon contraem Pokerus. Esse virus e totalmente benefico e adiciona um nivel de compatibilidade ao Pokemon em Genetica quando usado como host",
    "Automatically hides got Pokemon that are not new after a battle. Excluded from this setting are: New Pokemon, Iv's Ups and Shiny Pokemon": "Oculta automaticamente Pokemon obtidos que nao sao novos depois da batalha. Esta opcao nao oculta Pokemon novos, aumentos de IV e Pokemon shiny",
    "Moves cannot be freely switched at this moment": "Golpes nao podem ser trocados livremente neste momento",
    "Restricted moves cannot be freely switched during combat": "Golpes restritos nao podem ser trocados livremente durante combate",
    "Complete the tutorial first": "Complete o tutorial primeiro",
    "Complete the tutorial to access events": "Complete o tutorial para acessar eventos",
    "Defeat Team Leader Giovanni in VS mode to unlock": "Derrote o Lider da Equipe Giovanni no modo VS para desbloquear",
    "Defeat Gym Leader Brock in VS mode to unlock": "Derrote o Lider de Ginasio Brock no modo VS para desbloquear",
    "Defeat Legend Trainer Brendan in VS mode to unlock": "Derrote o Treinador Lendario Brendan no modo VS para desbloquear",
    "Defeat Elite Four Lance in VS mode to unlock": "Derrote Lance da Elite Four no modo VS para desbloquear",
    "Defeat Gym Leader Misty in VS mode to unlock": "Derrote a Lider de Ginasio Misty no modo VS para desbloquear",
    "Defeat Master Trainer Geeta in VS mode to unlock": "Derrote a Mestre Treinadora Geeta no modo VS para desbloquear",
    "Reward Received": "Recompensa recebida",
    "Next reward at": "Proxima recompensa em",
    "Next reward at score": "Proxima recompensa na pontuacao",
    "Select a Pokemon to add to the team": "Selecione um Pokemon para adicionar ao time",
    "Select a Pokemon to teach": "Selecione um Pokemon para ensinar",
    "Select a Pokemon to use the": "Selecione um Pokemon para usar",
    "Select a host Pokemon": "Selecione um Pokemon host",
    "Select a sample Pokemon": "Selecione um Pokemon amostra",
    "Select a Pokemon to train": "Selecione um Pokemon para treinar",
    "Select move to remember": "Selecione um golpe para lembrar",
    "No new moves to remember": "Nenhum golpe novo para lembrar",
    "New ability!": "Nova habilidade!",
    "(Uncommon!)": "(Incomum!)",
    "(Rare!)": "(Raro!)",
    "Click here to add tags": "Clique aqui para adicionar marcadores",
    "Create new tag": "Criar novo marcador",
    "Are you sure you want to delete this tag? It will be removed from all Pokemon": "Tem certeza que quer apagar este marcador? Ele sera removido de todos os Pokemon",
    "Tag Name": "Nome do marcador",
    "Select Icon": "Selecionar icone",
    "Tag Color": "Cor do marcador",
    "Save Tag": "Salvar marcador",
    "Tag Name Select Icon Tag Color #667eea Save Tag": "Nome do marcador Selecionar icone Cor do marcador #667eea Salvar marcador",
    "Restricted Moves": "Golpes restritos",
    "The training Pokemon has multiple restricted moves equipped!": "O Pokemon de treino tem varios golpes restritos equipados!",
    "Damage Dealt": "Dano causado",
    "Every 12h you might receive a random pokemon": "A cada 12h voce pode receber um Pokemon aleatorio",
    "Select an event": "Selecione um evento",
    "Available items will rotate in ...": "Itens disponiveis vao rotacionar em ...",
    "Select ingredients to add to the curry!": "Selecione ingredientes para adicionar ao curry!",
    "Select at least one ingredient first": "Selecione pelo menos um ingrediente primeiro",
    "During raids: Temporarily gained the next abilities for everyone in your team:": "Durante raids: as proximas habilidades foram ganhas temporariamente por todo o seu time:",
    "During raids: Gained the next abilities for everyone in your team:": "Durante raids: as proximas habilidades foram dadas para todo o seu time:",
    "Trainers": "Treinadores",
    "Highest Reached Floor:": "Maior andar alcancado:",
    "Highest Score:": "Maior pontuacao:",
    "Defeated:": "Derrotados:",
    "Operation finished!<br>Do you want to use a genetic-aiding item?": "Operacao concluida!<br>Quer usar um item de apoio genetico?",
    "The item will be consumed on use": "O item sera consumido ao usar",
    "Nothing but time will be lost": "Apenas tempo sera perdido",
    "Warning, high Power Cost! Only 5 out of 6 maximum IV's per stat will be inherited!": "Aviso, Custo de Poder alto! Apenas 5 de 6 IVs maximos por atributo serao herdados!",
    "Warning, very high Power Cost! Only 4 out of 6 maximum IV's per stat will be inherited!": "Aviso, Custo de Poder muito alto! Apenas 4 de 6 IVs maximos por atributo serao herdados!",
    "Warning, extreme Power Cost! Only 3 out of 6 maximum IV's per stat will be inherited!": "Aviso, Custo de Poder extremo! Apenas 3 de 6 IVs maximos por atributo serao herdados!",
    "Decreases Physical Attack by 50% and deals damage every turn": "Reduz o Ataque Fisico em 50% e causa dano todo turno",
    "Decreases Special Attack by 50% and deals damage every turn": "Reduz o Ataque Especial em 50% e causa dano todo turno",
    "Moves fail to deal damage": "Golpes falham ao causar dano",
    "50% chance for moves to fail to deal damage": "50% de chance de golpes falharem ao causar dano",
    "25% chance for moves to fail to deal damage and Speed is reduced by 75%": "25% de chance de golpes falharem ao causar dano e Velocidade e reduzida em 75%"
  };
  function replaceAllText(output, pairs) {
    for (const [from, to] of pairs) output = output.split(from).join(to);
    return output;
  }
  function translatePtGeneratedText(output) {
    const leading = output.match(/^\s*/)?.[0] || "";
    const trailing = output.match(/\s*$/)?.[0] || "";
    const trimmed = output.trim();
    if (ptExactText[trimmed]) return `${leading}${ptExactText[trimmed]}${trailing}`;

    output = replaceAllText(output, [
      [">Burn<", ">Queimadura<"],
      [">Freeze<", ">Congelamento<"],
      [">Paralysis<", ">Paralisia<"],
      [">Poisoned<", ">Envenenado<"],
      [">Sleep<", ">Sono<"],
      [">Confused<", ">Confuso<"],
      [">Embargo<", ">Embargo<"],
      [">Sunny<", ">Sol<"],
      [">Rainy<", ">Chuva<"],
      [">Sandstorm<", ">Tempestade de Areia<"],
      [">Hail<", ">Granizo<"],
      [">Foggy<", ">Neblina<"],
      [">Electric Terrain<", ">Campo Eletrico<"],
      [">Grassy Terrain<", ">Campo de Grama<"],
      [">Misty Terrain<", ">Campo Nebuloso<"],
      [">Trick Room<", ">Trick Room<"],
      [">Weird Room<", ">Weird Room<"],
      [">Cross Room<", ">Cross Room<"],
      [">Light Screen<", ">Light Screen<"],
      [">Safeguard<", ">Safeguard<"]
    ]);

    output = output
      .replace(/Halves the damage received of ([A-Za-z]+)-type moves/g, (_, type) => `Reduz pela metade o dano recebido de golpes do tipo ${ptType(type)}`)
      .replace(/Halves damage received from ([A-Za-z]+) and ([A-Za-z]+)-type moves/g, (_, a, b) => `Reduz pela metade o dano recebido de golpes dos tipos ${ptType(a)} e ${ptType(b)}`)
      .replace(/Increases the power of ([A-Za-z]+)-type moves by ([0-9]+)% below ([0-9]+)% HP/g, (_, type, amount, hp) => `Aumenta o poder de golpes do tipo ${ptType(type)} em ${amount}% abaixo de ${hp}% de HP`)
      .replace(/Nullifies received ([A-Za-z]+)-type moves and increases Speed by ([0-9]+)% after being hit with one/g, (_, type, amount) => `Anula golpes recebidos do tipo ${ptType(type)} e aumenta a Velocidade em ${amount}% depois de ser atingido por um`)
      .replace(/Nullifies received ([A-Za-z]+)-type moves/g, (_, type) => `Anula golpes recebidos do tipo ${ptType(type)}`)
      .replace(/([A-Za-z]+)-type moves become ([A-Za-z]+)-type moves, and their power is multiplied by (x[0-9.]+)/g, (_, from, to, mult) => `Golpes do tipo ${ptType(from)} se tornam golpes do tipo ${ptType(to)}, e seu poder e multiplicado por ${mult}`)
      .replace(/All moves become ([A-Za-z]+)-type moves, and their power is multiplied by (x[0-9.]+)/g, (_, type, mult) => `Todos os golpes se tornam golpes do tipo ${ptType(type)}, e seu poder e multiplicado por ${mult}`)
      .replace(/([A-Za-z]+) and ([A-Za-z]+)-type moves are executed (x[0-9.]+) faster than usual/g, (_, a, b, mult) => `Golpes dos tipos ${ptType(a)} e ${ptType(b)} sao executados ${mult} mais rapido que o normal`)
      .replace(/([A-Za-z]+) and ([A-Za-z]+) moves are executed (x[0-9.]+) faster than usual/g, (_, a, b, mult) => `Golpes dos tipos ${ptType(a)} e ${ptType(b)} sao executados ${mult} mais rapido que o normal`)
      .replace(/Super-effective against ([A-Za-z]+)-types/g, (_, type) => `Super efetivo contra Pokemon do tipo ${ptType(type)}`);

    output = output
      .replace(/([0-9]+)% chance to increase (enemy )?(all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([0-9]+)%/g, (_, chance, enemy, stat, amount) => `${chance}% de chance de aumentar ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${amount}%`)
      .replace(/([0-9]+)% chance to decrease (enemy )?(all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([0-9]+)%/g, (_, chance, enemy, stat, amount) => `${chance}% de chance de reduzir ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${amount}%`)
      .replace(/([0-9]+)% chance to inflict/g, (_, chance) => `${chance}% de chance de causar`)
      .replace(/Increases (enemy )?(highest stat|all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([x0-9.]+%?)/g, (_, enemy, stat, amount) => `Aumenta ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${ptAmount(amount)}`)
      .replace(/Increase (enemy )?(highest stat|all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([x0-9.]+%?)/g, (_, enemy, stat, amount) => `Aumenta ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${ptAmount(amount)}`)
      .replace(/Decreases (enemy )?(highest stat|all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([x0-9.]+%?)/g, (_, enemy, stat, amount) => `Reduz ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${ptAmount(amount)}`)
      .replace(/Decrease (enemy )?(highest stat|all Stats|Special Attack|Special Defense|Attack|Defense|Speed) by ([x0-9.]+%?)/g, (_, enemy, stat, amount) => `Reduz ${ptStat(stat)}${enemy ? " do inimigo" : ""} em ${ptAmount(amount)}`)
      .replace(/Increases (Special Attack|Special Defense|Attack|Defense|Speed) and (Special Attack|Special Defense|Attack|Defense|Speed) by ([0-9]+)%/g, (_, a, b, amount) => `Aumenta ${ptStat(a)} e ${ptStat(b)} em ${amount}%`)
      .replace(/Decreases (Special Attack|Special Defense|Attack|Defense|Speed) and (Special Attack|Special Defense|Attack|Defense|Speed) by ([0-9]+)%/g, (_, a, b, amount) => `Reduz ${ptStat(a)} e ${ptStat(b)} em ${amount}%`);

    output = replaceAllText(output, [
      ["No additional effects", "Sem efeitos adicionais"],
      ["Prevents negative status effects while on ", "Impede efeitos de status negativos durante "],
      ["Prevents negative stat changes and status effects while on ", "Impede reducoes de atributos e efeitos de status durante "],
      ["Prevents the lowering of any Attack stat", "Impede a reducao de qualquer atributo de ataque"],
      ["Prevents the lowering of any Defense stat", "Impede a reducao de qualquer atributo de defesa"],
      ["Prevents all stat decreases", "Impede todas as reducoes de atributos"],
      ["50% chance for received Status Effects to miss", "50% de chance de efeitos de status recebidos falharem"],
      ["Grants immunity to ", "Concede imunidade a "],
      ["Prevents all Pokemon on your team from ", "Impede que todos os Pokemon do time recebam "],
      ["Status effects are cleared when switching Pokemon", "Efeitos de status sao removidos ao trocar de Pokemon"],
      ["Inflicts active status effects to the attacker aswell on the moment of application", "Tambem aplica efeitos de status ativos ao atacante no momento da aplicacao"],
      ["Increases the weight of rare item drops by 1% (Can stack). Works always for everyone regardless of the user", "Aumenta o peso de drops raros de itens em 1% (acumula). Funciona sempre para todos, independentemente do usuario"],
      ["Increases the weight of rare Pokemon by 1% (Can stack). Works always for everyone regardless of the user", "Aumenta o peso de Pokemon raros em 1% (acumula). Funciona sempre para todos, independentemente do usuario"],
      ["Positive secondary effect of damaging moves are removed, and their damage is multiplied by x1.25", "Efeitos secundarios positivos de golpes de dano sao removidos, e o dano e multiplicado por x1.25"],
      ["Increases Same-Type-Attack-Bonus by +0.2", "Aumenta STAB em +0.2"],
      ["Increases Cross-Power by +0.3", "Aumenta Poder Cruzado em +0.3"],
      ["Increases Cross-Power by +0.5", "Aumenta Poder Cruzado em +0.5"],
      ["Damage received is halved when over 50% HP", "Dano recebido e reduzido pela metade acima de 50% de HP"],
      ["Moves that hit multiple times always hit their maximum amount", "Golpes multi-hit sempre acertam a quantidade maxima"],
      ["Moves that execute slower than usual have their base power multiplied by x1.5", "Golpes mais lentos que o normal tem o poder base multiplicado por x1.5"],
      ["Moves that execute faster than usual have their base power multiplied by x2", "Golpes mais rapidos que o normal tem o poder base multiplicado por x2"],
      ["Decreases fatigue damage of the user by x2", "Reduz o dano de fadiga do usuario em x2"],
      ["Multiply the damage dealt by x1.5 if the target has a status effect", "Multiplica o dano causado por x1.5 se o alvo tiver um efeito de status"],
      ["Decreases the damage of all ghost moves by 25% (Can stack). Works always for everyone regardless of the user", "Reduz o dano de todos os golpes Fantasma em 25% (acumula). Funciona sempre para todos, independentemente do usuario"],
      ["All hits become super-effective regardless of the typing", "Todos os acertos viram super efetivos independentemente do tipo"],
      ["Increases the chance of encountering a wild shiny pokemon by 15%. Works always for everyone regardless of the user", "Aumenta em 15% a chance de encontrar Pokemon shiny selvagem. Funciona sempre para todos, independentemente do usuario"],
      ["Moves that are resisted by typing do instead normal damage", "Golpes resistidos por tipo causam dano normal"],
      ["Secondary effect of moves are executed twice", "Efeitos secundarios dos golpes sao executados duas vezes"],
      ["Changes the type of the user to match the type of the used move", "Muda o tipo do usuario para combinar com o tipo do golpe usado"],
      ["Moves are executed a second time, at half power", "Golpes sao executados uma segunda vez, com metade do poder"],
      ["Decreases Physical Attack by 50% and deals damage every turn", "Reduz o Ataque Fisico em 50% e causa dano todo turno"],
      ["Decreases Special Attack by 50% and deals damage every turn", "Reduz o Ataque Especial em 50% e causa dano todo turno"],
      ["Moves fail to deal damage", "Golpes falham ao causar dano"],
      ["50% chance for moves to fail to deal damage", "50% de chance de golpes falharem ao causar dano"],
      ["25% chance for moves to fail to deal damage and Speed is reduced by 75%", "25% de chance de golpes falharem ao causar dano e Velocidade e reduzida em 75%"],
      ["Increases the damage of Fire-Type moves by 50% and decreases the damage of Water-Type moves by 50%", "Aumenta o dano de golpes do tipo Fogo em 50% e reduz o dano de golpes do tipo Agua em 50%"],
      ["Increases the damage of Water-Type moves by 50% and decreases the damage of Fire-Type moves by 50%", "Aumenta o dano de golpes do tipo Agua em 50% e reduz o dano de golpes do tipo Fogo em 50%"],
      ["Increases the damage of Rock and Ground-Type moves by 50%", "Aumenta o dano de golpes dos tipos Pedra e Terrestre em 50%"],
      ["Increases the damage of Ice-Type moves by 50%", "Aumenta o dano de golpes do tipo Gelo em 50%"],
      ["Increases the damage of Dark and Ghost-Type moves by 50%", "Aumenta o dano de golpes dos tipos Sombrio e Fantasma em 50%"],
      ["Increases the damage of Electric and Steel-Type moves by 50%", "Aumenta o dano de golpes dos tipos Eletrico e Aco em 50%"],
      ["Increases the damage of Grass and Bug-Type moves by 50%", "Aumenta o dano de golpes dos tipos Grama e Inseto em 50%"],
      ["Increases the damage of Fairy and Psychic-Type moves by 50%", "Aumenta o dano de golpes dos tipos Fada e Psiquico em 50%"],
      ["Slower Pokemon become faster, faster Pokemon become slower. Additionally, multiplies the damage based on how slow the Pokemon originally was by x1.0 to x1.5", "Pokemon mais lentos ficam mais rapidos, e Pokemon mais rapidos ficam mais lentos. Alem disso, multiplica o dano de x1.0 a x1.5 com base na lentidao original do Pokemon"],
      ["Copies all attack and defense base stats of the enemy", "Copia todos os atributos base de ataque e defesa do inimigo"],
      ["Increases the damage dealt by cross-power by 30%", "Aumenta o dano causado por Poder Cruzado em 30%"],
      ["Super-effective damage dealt to your team is reduced to neutral", "Dano super efetivo causado ao seu time e reduzido para neutro"],
      ["Protects your team from status effects and stat reductions", "Protege seu time contra efeitos de status e reducoes de atributos"],
      ["Decreases the damage dealt by physical attacks by 75%", "Reduz o dano causado por ataques fisicos em 75%"],
      ["Pick a difficulty for the next trainer (Right click/long tap to see the field effect details)", "Escolha uma dificuldade para o proximo treinador (clique com o botao direito ou segure o toque para ver detalhes do efeito de campo)"],
      ["Level 100 Reward:", "Recompensa nivel 100:"],
      ["Level 125 Reward:", "Recompensa nivel 125:"],
      ["Level 150 Reward:", "Recompensa nivel 150:"],
      ["Due to the vs rewards update you have been rewarded for your defeated trainers:", "Por causa da atualizacao das recompensas VS, voce recebeu recompensas pelos treinadores derrotados:"],
      ["Howdy! I have been assigned to show the ropes<br>Let's start by getting new pokemon shall we? Select \"Travel\" on the top left menu", "Ola! Fui designado para mostrar o basico<br>Vamos comecar pegando novos Pokemon. Selecione \"Viajar\" no menu superior esquerdo"],
      ["Howdy! I have been assigned to show the ropes Let's start by getting new pokemon shall we? Select \"Travel\" on the top left menu", "Ola! Fui designado para mostrar o basico. Vamos comecar pegando novos Pokemon. Selecione \"Viajar\" no menu superior esquerdo"],
      ["You can right click/long tap almost everything on the screen for more info! You can also do this within the info itself too. Try going into the first Wild Area to start catching Pokemon", "Voce pode clicar com o botao direito ou segurar o toque em quase tudo na tela para ver mais informacoes. Isso tambem funciona dentro das proprias informacoes. Tente entrar na primeira Area Selvagem para comecar a capturar Pokemon"],
      ["Right click/long tap a pokemon in your team to set their moves, you can also do this while in battle. Press the + symbol next to the Pokemon to assign items<br>Once you are ready, press Save and Go! at the top of the screen", "Clique com o botao direito ou segure o toque em um Pokemon do time para definir os golpes. Voce tambem pode fazer isso durante a batalha. Pressione o simbolo + ao lado do Pokemon para equipar itens<br>Quando estiver pronto, pressione Salvar e ir! no topo da tela"],
      ["Right click/long tap a pokemon in your team to set their moves, you can also do this while in battle. Press the + symbol next to the Pokemon to assign items Once you are ready, press Save and Go! at the top of the screen", "Clique com o botao direito ou segure o toque em um Pokemon do time para definir os golpes. Voce tambem pode fazer isso durante a batalha. Pressione o simbolo + ao lado do Pokemon para equipar itens. Quando estiver pronto, pressione Salvar e ir! no topo da tela"],
      ["You can check a more in-depth explanation about stats and battle mechanics in the Guide menu. For now, I will take a break... Enjoy your stay!", "Voce pode ver uma explicacao mais detalhada sobre atributos e mecanicas de batalha no menu Guia. Por enquanto, vou fazer uma pausa... Aproveite!"],
      ["Auto-Refight is active!", "Auto-Refight esta ativo!"],
      ["Auto-Refight Tickets remaining", "Auto-Refight Tickets restantes"],
      ["Wont consume an Auto-Refight Ticket", "Nao consome Auto-Refight Ticket"],
      ["Click to disable it", "Clique para desativar"],
      ["(Uncommon!)", "(Incomum!)"],
      ["(Rare!)", "(Raro!)"],
      ["Nope", "Nao"],
      ["Yeah!", "Sim!"],
      ["Operation finished! Do you want to use a genetic-aiding item?", "Operacao concluida! Quer usar um item de apoio genetico?"],
      ["Select the seasonal event to start. It will last for the 10 following days, and will get replaced by currently-ongoing ones. However, the seasonal shop of that event wont open", "Selecione o evento sazonal para iniciar. Ele durara pelos proximos 10 dias e sera substituido por eventos ativos no momento. A loja sazonal desse evento nao abrira"],
      ["Select ingredients to add to the curry!", "Selecione ingredientes para adicionar ao curry!"],
      ["New Wild Area unlocked", "Nova Area Selvagem desbloqueada"],
      ["New Dungeon:", "Nova Masmorra:"],
      ["Mystery Gift unlocked", "Presente Misterioso desbloqueado"],
      ["Export Reward unlocked", "Recompensa de Exportacao desbloqueada"],
      ["Poke-Mart unlocked", "Loja desbloqueada"],
      ["Level Training unlocked", "Treino de nivel desbloqueado"],
      ["Training unlocked", "Treino desbloqueado"],
      ["Battle Frontier unlocked", "Fronteira de Batalha desbloqueada"],
      ["Elite Event tab unlocked", "Aba de Eventos Elite desbloqueada"],
      ["Master League is now available in the Battle Frontier", "Master League agora esta disponivel na Fronteira de Batalha"],
      ["Tier I Event Raids unlocked", "Raids de Evento Tier I desbloqueadas"],
      ["Tier IV Event Raids unlocked", "Raids de Evento Tier IV desbloqueadas"],
      ["Battle Tower", "Torre de Batalha"],
      ["Battle Factory", "Fabrica de Batalha"],
      ["Battle Arena", "Arena de Batalha"],
      ["Battle Frontier", "Fronteira de Batalha"],
      ["VS Trainers", "Treinadores VS"],
      ["Trainers", "Treinadores"],
      ["Highest Reached Floor:", "Maior andar alcancado:"],
      ["Highest Score:", "Maior pontuacao:"],
      ["Defeated:", "Derrotados:"],
      ["This is a Hidden Ability. Hidden abilities are unlocked via Ability Capsules or via Training, and they work alongside your regular ability", "Esta e uma Habilidade Oculta. Habilidades Ocultas sao desbloqueadas por Ability Capsules ou pelo Treino, e funcionam junto da habilidade normal"],
      ["Right Click/Long press to see the details", "Clique com o botao direito ou segure o toque para ver os detalhes"],
      ["Trainers have twice the health. Only applies to VS Trainers", "Treinadores tem o dobro de vida. Aplica apenas a treinadores VS"],
      ["If any of your Pokemon get defeated while battling a trainer of VS Trainers, it will permanently be unusuable until you turn this mode off", "Se qualquer Pokemon seu for derrotado lutando contra um treinador VS, ele ficara permanentemente inutilizavel ate voce desligar este modo"],
      ["All of your Pokemon have functionally max IVs regardless of their actual IVs. This can be toggled off without any permanent changes", "Todos os seus Pokemon funcionam como se tivessem IVs maximos, independentemente dos IVs reais. Isso pode ser desligado sem mudancas permanentes"],
      ["Fatigue damage is reduced by x3", "Dano de fadiga e reduzido em x3"],
      ["There are no side-effects to this modifier", "Este modificador nao tem efeitos colaterais"],
      ["Every 12h you can select up to three abilities to be active for your entire team during raids for 1 hour. These abilities follow the same rules as regular abilities, and wont stack with already existing ones", "A cada 12h voce pode selecionar ate tres habilidades para ficarem ativas em todo o time durante raids por 1 hora. Essas habilidades seguem as mesmas regras das habilidades normais e nao acumulam com habilidades ja existentes"],
      ["Increases the Attack by x1.5, but prevents them from switching", "Aumenta o Ataque em x1.5, mas impede trocas"],
      ["Prevents the enemy to use the move in the slot embargo was used. This is treated as a status effect", "Impede o inimigo de usar o golpe no slot em que Embargo foi usado. Isso e tratado como efeito de status"],
      ["User transfers all of its stat changes and status to a the entire team and faints. This move can only be present once per team", "O usuario transfere todas as mudancas de atributos e status para todo o time e desmaia. Este golpe so pode estar presente uma vez por time"],
      ["Decreases Defense, Special Defense and Speed by 50%", "Reduz Defesa, Defesa Especial e Velocidade em 50%"],
      ["Decreases Defense, Special Defense 50%", "Reduz Defesa e Defesa Especial em 50%"],
      ["Attacks x1.2 faster than usual", "Ataca x1.2 mais rapido que o normal"],
      ["Attacks x1.5 faster than usual", "Ataca x1.5 mais rapido que o normal"],
      ["Attacks x2 faster than usual", "Ataca x2 mais rapido que o normal"],
      ["Attacks x3 faster than usual", "Ataca x3 mais rapido que o normal"],
      ["Attacks x1.2 slower than usual", "Ataca x1.2 mais devagar que o normal"],
      ["Attacks x1.4 slower than usual", "Ataca x1.4 mais devagar que o normal"],
      ["Attacks x1.5 slower than usual", "Ataca x1.5 mais devagar que o normal"],
      ["Attacks x2 slower than usual", "Ataca x2 mais devagar que o normal"],
      ["Hits 2 times", "Acerta 2 vezes"],
      ["Hits 3 times", "Acerta 3 vezes"],
      ["Hits 2-5 times", "Acerta 2-5 vezes"],
      ["Inflicts ", "Causa "],
      ["Changes the weather to ", "Muda o clima/campo para "],
      ["Switches to the next party member", "Troca para o proximo membro do time"],
      ["Power doubles if the target has a status effect", "O poder dobra se o alvo tiver um efeito de status"],
      ["Power doubles if the target is Flying-Type", "O poder dobra se o alvo for do tipo Voador"],
      ["Power doubles if the target is ", "O poder dobra se o alvo estiver "],
      ["Power doubles if the user is not holding any item", "O poder dobra se o usuario nao estiver segurando item"],
      ["Power doubles if the user is Paralyzed, Burned or Poisoned", "O poder dobra se o usuario estiver Paralisado, Queimado ou Envenenado"],
      ["Power randomly varies from x1 to x8", "O poder varia aleatoriamente de x1 a x8"],
      ["Power increases by x1.2-1.5 if Defense/Special Defense is risen", "O poder aumenta em x1.2-1.5 se Defesa/Defesa Especial estiver aumentada"],
      ["Power increases by x1.2-1.5 if Speed is risen", "O poder aumenta em x1.2-1.5 se Velocidade estiver aumentada"],
      ["Increases base power by 30 for every unique stat up of the user", "Aumenta o poder base em 30 para cada atributo unico aumentado no usuario"],
      ["Multiplies base power by 1.2x everytime its used, up to 5 times. Depletes all stacks upon switching Pokemon", "Multiplica o poder base por 1.2x cada vez que e usado, ate 5 vezes. Zera os acumulos ao trocar de Pokemon"],
      ["Multiplies base power by 1.3x everytime its used, up to 3 times. Depletes all stacks upon switching Pokemon", "Multiplica o poder base por 1.3x cada vez que e usado, ate 3 vezes. Zera os acumulos ao trocar de Pokemon"],
      ["Multiplies base power by 1.15x everytime its used, up to 10 times. Depletes all stacks upon switching Pokemon", "Multiplica o poder base por 1.15x cada vez que e usado, ate 10 vezes. Zera os acumulos ao trocar de Pokemon"],
      ["Perform the first move of the oponent, at double the damage", "Executa o primeiro golpe do oponente com o dobro do dano"],
      ["Perform the first move of the oponent", "Executa o primeiro golpe do oponente"],
      ["This is an Egg Move. Egg moves can be learnt with genetics when using this Pokemon as a host, using a sample that knows said egg move (usually in the form of Signature moves), at regular move transfer odds", "Este e um Golpe Ovo. Golpes Ovo podem ser aprendidos com Genetica usando este Pokemon como host e uma amostra que conheca o golpe, normalmente por meio de Golpes Assinatura, nas chances normais de transferencia"],
      ["This is a Signature Move. Signature moves will automatically be learnt at level 100", "Este e um Golpe Assinatura. Golpes Assinatura sao aprendidos automaticamente no nivel 100"],
      ["User performs any move at random", "O usuario executa qualquer golpe aleatorio"],
      ["Executes the first move slot", "Executa o primeiro slot de golpe"],
      ["Faints the user", "Derrota o usuario"],
      ["Steals the stat changes of the enemy", "Rouba as mudancas de atributos do inimigo"],
      ["Bypasses all defense buffs", "Ignora todos os buffs de defesa"],
      ["Can hit regardless of the typing", "Pode acertar independentemente do tipo"],
      ["Moves always hit regardless of the type", "Golpes sempre acertam independentemente do tipo"],
      ["Removes all status effect for the entire party", "Remove todos os efeitos de status de todo o time"],
      ["Removes ", "Remove "],
      [" for the entire party", " de todo o time"],
      [" to the entire team", " para todo o time"],
      [" on the user", " no usuario"],
      [" when attacked", " ao ser atacado"],
      [" when defeating a Pokemon", " ao derrotar um Pokemon"],
      [" when the opposing Pokemon enters the battle", " quando o Pokemon adversario entra na batalha"],
      [" when entering or switching into the battle", " ao entrar ou trocar para a batalha"],
      [" if afflicted with a status effect", " se estiver com um efeito de status"],
      [" if no item is being held", " se nao estiver segurando item"],
      [" and nullifies the damage overtime caused by it", " e anula o dano ao longo do tempo causado por ele"],
      [" and nullifies the stat redution of the condition", " e anula a reducao de atributo da condicao"],
      [" and decreases enemy ", " e reduz "],
      [" and increases enemy ", " e aumenta "],
      [" and decreases ", " e reduz "],
      [" and increases ", " e aumenta "],
      [" but increases enemy ", " mas aumenta "],
      [" but decreases ", " mas reduz "],
      [" weather", ""],
      ["Pokemon", "Pokemon"],
      ["base poder", "poder base"],
      ["user", "usuario"],
      ["target", "alvo"],
      ["enemy", "inimigo"],
      ["status effect", "efeito de status"],
      ["status effects", "efeitos de status"],
      ["super-effective", "super efetivo"],
      ["Super-effective", "Super efetivo"],
      ["temporary", "temporario"],
      ["type", "tipo"],
      ["the entire team", "todo o time"]
    ]);
    output = output
      .replace(/\b(e reduz|e aumenta|mas reduz|mas aumenta) (Special Attack|Special Defense|Attack|Defense|Speed|all Stats) by ([x0-9.]+%?)/g, (_, action, stat, amount) => `${action} ${ptStat(stat)} em ${ptAmount(amount)}`)
      .replace(/\b(reduz|aumenta) (Special Attack|Special Defense|Attack|Defense|Speed|all Stats) by ([x0-9.]+%?)/g, (_, action, stat, amount) => `${action} ${ptStat(stat)} em ${ptAmount(amount)}`)
      .replace(/Increases the Damage dealt by ([x0-9.]+) when afflicted with/g, (_, amount) => `Aumenta o dano causado em ${amount} quando estiver com`)
      .replace(/Increases the Damage dealt by ([x0-9.]+) for every team member defeated/g, (_, amount) => `Aumenta o dano causado em ${amount} para cada membro do time derrotado`)
      .replace(/Increases the highest stat of the usuario by ([0-9]+)%/g, (_, amount) => `Aumenta o maior atributo do usuario em ${amount}%`)
      .replace(/\bbase poder\b/g, "poder base")
      .replace(/Cross-Poder/g, "Poder Cruzado")
      .replace(/\bmoves\b/g, "golpes")
      .replace(/\bmove\b/g, "golpe");
    return output;
  }
  function translateText(text) {
    const language = getLanguage();
    if (language === "en" || text === undefined || text === null) return text;
    let output = String(text);
    const replacements = data[language]?.replacements || {};
    for (const [from, to] of Object.entries(replacements)) output = output.split(from).join(to);
    if (language === "pt") output = translatePtGeneratedText(output);
    return output;
  }
  function translateExactText(text) {
    const language = getLanguage();
    if (language === "en" || text === undefined || text === null) return text;
    const output = String(text);
    if (language !== "pt") return output;
    const leading = output.match(/^\s*/)?.[0] || "";
    const trailing = output.match(/\s*$/)?.[0] || "";
    const trimmed = output.trim();
    return ptExactText[trimmed] ? `${leading}${ptExactText[trimmed]}${trailing}` : output;
  }
  function applyStaticTranslations(root = document) {
    const language = getLanguage();
    document.documentElement.lang = language === "pt" ? "pt-BR" : "en";
    root.querySelectorAll("[data-i18n]").forEach(element => { element.textContent = t(element.dataset.i18n, element.textContent); });
    root.querySelectorAll("[data-i18n-placeholder]").forEach(element => { element.setAttribute("placeholder", t(element.dataset.i18nPlaceholder, element.getAttribute("placeholder") || "")); });
    const select = document.getElementById("settings-language");
    if (select) select.value = language;
    if (language !== "en") applyDynamicTranslations(root === document ? document.body : root);
  }
  function applyDynamicTranslations(root = document) {
    if (getLanguage() === "en" || !root || !document.createTreeWalker) return;
    const ignoredTags = new Set(["SCRIPT", "STYLE", "TEXTAREA", "INPUT", "OPTION"]);
    const walker = document.createTreeWalker(root, 4, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || ignoredTags.has(parent.tagName)) return 2;
        if (!node.nodeValue || !node.nodeValue.trim()) return 2;
        return 1;
      }
    });
    const nodes = [];
    let node = walker.nextNode();
    while (node) {
      nodes.push(node);
      node = walker.nextNode();
    }
    nodes.forEach(textNode => {
      const title = textNode.parentElement?.closest?.("#tooltipTitle");
      textNode.nodeValue = title ? translateExactText(textNode.nodeValue) : translateText(textNode.nodeValue);
    });
  }
  function safeCall(callback) { try { callback(); } catch (error) {} }
  function refreshRenderedText() {
    safeCall(() => { if (typeof setGuide === "function") setGuide(); });
    safeCall(() => { if (typeof updateSettings === "function") updateSettings(); });
    safeCall(() => { if (typeof updatePreviewTeam === "function") updatePreviewTeam(); });
    safeCall(() => { if (typeof updateTeamPkmn === "function") updateTeamPkmn(); });
    safeCall(() => { if (typeof updateItemBag === "function") updateItemBag(); });
    safeCall(() => { if (typeof updateItemShop === "function") updateItemShop(); });
    safeCall(() => { if (typeof updateDictionary === "function") updateDictionary(); });
    safeCall(() => { if (typeof updateWildPkmn === "function") updateWildPkmn(); });
    safeCall(() => { applyDynamicTranslations(document.body); });
  }
  window.UltraLocale = { getLanguage, setLanguage, t, formatName, guideName, guideDescription, translateText, applyStaticTranslations, applyDynamicTranslations, refreshRenderedText };
})();
